FROM ruby:3.4-alpine

RUN apk add --no-cache \
  build-base \
  postgresql-dev \
  yaml-dev \
  tzdata \
  git

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "bundle exec rails s -b 0.0.0.0"]
